"""Replay a clip through the detector + debouncer and report what would have happened.

Brief §6.2. Primary tool for tuning `conf_threshold` and `consecutive_hits`
against real chamber footage. Reads from either:

* A folder of JPEG frames (lexically sorted).
* A directory holding a single video (decoded with cv2 — live path only).

Per-frame timeline goes to stdout; a JSON summary (frame index, would-fire
timestamps, settings used) goes to a configurable path so the run can be
diffed against prior tuning sessions.

Two model paths are supported:

* `--model marker` uses the test-fixture marker detector (works without any
  live deps and against fixtures generated by `mock_printer.make_jpeg`).
* `--model path/to/weights.pt` loads Ultralytics YOLO weights (live).
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from collections.abc import Iterable, Iterator, Sequence

from spaghetti_guard.detector import Debouncer, FailureDetector, FrameResult

logger = logging.getLogger("replay")


SUPPORTED_IMAGE_SUFFIXES = {".jpg", ".jpeg"}


@dataclass
class FrameRow:
    index: int
    path: str
    hit: bool
    conf: float
    best_class: str | None
    streak_after: int
    would_fire: bool


@dataclass
class ReplayReport:
    clip: str
    frame_count: int
    fired_indices: list[int]
    settings: dict
    duration_s: float
    rows: list[FrameRow]

    def to_dict(self) -> dict:
        return {
            "clip": self.clip,
            "frame_count": self.frame_count,
            "fired_indices": self.fired_indices,
            "settings": self.settings,
            "duration_s": self.duration_s,
            "rows": [asdict(r) for r in self.rows],
        }


# ---------------------------------------------------------------------------
# Frame sources
# ---------------------------------------------------------------------------


def iter_jpegs_from_folder(folder: Path) -> Iterator[tuple[Path, bytes]]:
    files = sorted(
        p for p in folder.iterdir() if p.is_file() and p.suffix.lower() in SUPPORTED_IMAGE_SUFFIXES
    )
    for p in files:
        yield p, p.read_bytes()


def iter_jpegs_from_video(video_path: Path) -> Iterator[tuple[Path, bytes]]:  # pragma: no cover
    """Live path: decode a video to JPEG bytes via cv2."""
    import cv2  # type: ignore

    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError(f"could not open video {video_path}")
    idx = 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        ok2, buf = cv2.imencode(".jpg", frame)
        if not ok2:
            continue
        synthetic = video_path.with_name(f"{video_path.stem}-{idx:06d}.jpg")
        yield synthetic, buf.tobytes()
        idx += 1
    cap.release()


# ---------------------------------------------------------------------------
# Detector adapters
# ---------------------------------------------------------------------------


def _build_marker_detector(*, failure_classes: Sequence[str], conf_threshold: float) -> FailureDetector:
    from verification.mock_printer import MARKER_FAILURE, extract_marker

    class _Box:
        __slots__ = ("cls_name", "conf")

        def __init__(self, cls_name: str, conf: float) -> None:
            self.cls_name = cls_name
            self.conf = conf

    class _MarkerYolo:
        def predict(self, image, **kwargs):
            marker = extract_marker(image)
            if marker == MARKER_FAILURE:
                return [_Box(next(iter(failure_classes)), 0.95)]
            return []

    return FailureDetector(
        _MarkerYolo(),
        failure_classes=failure_classes,
        conf_threshold=conf_threshold,
        decoder=lambda j: j,
    )


def _build_yolo_detector(model_path: Path, *, failure_classes: Sequence[str], conf_threshold: float) -> FailureDetector:  # pragma: no cover
    from spaghetti_guard.detector import decode_jpeg, load_yolo_model

    # FailureDetector flattens Ultralytics Results natively.
    return FailureDetector(
        load_yolo_model(model_path),
        failure_classes=failure_classes,
        conf_threshold=conf_threshold,
        decoder=decode_jpeg,
    )


# ---------------------------------------------------------------------------
# Core replay
# ---------------------------------------------------------------------------


def replay(
    frames: Iterable[tuple[Path, bytes]],
    detector: FailureDetector,
    *,
    debounce_window: int,
    cooldown_frames: int = 30,
    clip_label: str = "clip",
) -> ReplayReport:
    """Run detector + debouncer over the clip and record per-frame outcomes.

    `cooldown_frames` models the Guard's post-fire COOLDOWN: after a would-fire
    frame, the next `cooldown_frames` frames are skipped from debounce
    accounting so we report at most one fire per cooldown window. This matches
    the live behavior and makes the report useful for threshold tuning.
    """
    debouncer = Debouncer(window=debounce_window)
    rows: list[FrameRow] = []
    fired: list[int] = []
    started = time.monotonic()
    cooldown_remaining = 0

    for idx, (path, payload) in enumerate(frames):
        result: FrameResult = detector.is_failure_frame(payload)
        in_cooldown = cooldown_remaining > 0
        if in_cooldown:
            cooldown_remaining -= 1
            would_fire = False
            streak_after = 0
        else:
            debouncer.update(result.hit)
            would_fire = debouncer.confirmed()
            streak_after = debouncer.streak()
        rows.append(
            FrameRow(
                index=idx,
                path=str(path),
                hit=result.hit,
                conf=result.conf,
                best_class=result.best_class,
                streak_after=streak_after,
                would_fire=would_fire,
            )
        )
        if would_fire:
            fired.append(idx)
            debouncer.reset()
            cooldown_remaining = cooldown_frames

    return ReplayReport(
        clip=clip_label,
        frame_count=len(rows),
        fired_indices=fired,
        settings={
            "debounce_window": debounce_window,
            "cooldown_frames": cooldown_frames,
            "failure_classes": list(detector._failure_classes),
            "conf_threshold": detector._conf_threshold,
        },
        duration_s=time.monotonic() - started,
        rows=rows,
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _emit_timeline(report: ReplayReport, *, stream=sys.stdout) -> None:
    stream.write(
        f"clip: {report.clip}  frames: {report.frame_count}  "
        f"fired_at: {report.fired_indices or '-'}  "
        f"window: {report.settings['debounce_window']}  "
        f"thresh: {report.settings['conf_threshold']}\n"
    )
    for r in report.rows:
        flag = "FIRE" if r.would_fire else ("hit " if r.hit else "    ")
        stream.write(
            f"  [{r.index:05d}] {flag} conf={r.conf:.2f} streak={r.streak_after} {r.best_class or '-'}\n"
        )


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Replay a clip through the failure detector + debouncer")
    p.add_argument("clip", type=Path, help="folder of JPEG frames OR a video file")
    p.add_argument(
        "--model",
        default="marker",
        help="'marker' (test path; reads mock_printer markers) or a path to YOLO weights",
    )
    p.add_argument("--conf", type=float, default=0.55, help="confidence threshold")
    p.add_argument("--window", type=int, default=6, help="N-of-N debounce window")
    p.add_argument(
        "--cooldown-frames",
        type=int,
        default=30,
        help="frames to skip after a fire (mirrors Guard COOLDOWN)",
    )
    p.add_argument(
        "--classes",
        nargs="+",
        default=["spaghetti", "detachment", "blob", "failure"],
        help="failure class names",
    )
    p.add_argument("--json-out", type=Path, help="write JSON report to this path")
    p.add_argument("--quiet", action="store_true", help="suppress per-frame stdout timeline")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    logging.basicConfig(level=logging.WARNING)

    clip_path: Path = args.clip
    if clip_path.is_dir():
        frames = list(iter_jpegs_from_folder(clip_path))
    elif clip_path.is_file() and clip_path.suffix.lower() in {".mp4", ".mov", ".mkv"}:
        frames = list(iter_jpegs_from_video(clip_path))
    elif clip_path.is_file() and clip_path.suffix.lower() in SUPPORTED_IMAGE_SUFFIXES:
        frames = [(clip_path, clip_path.read_bytes())]
    else:
        logger.error("unsupported clip path: %s", clip_path)
        return 2

    if not frames:
        logger.error("no frames found at %s", clip_path)
        return 2

    if args.model == "marker":
        detector = _build_marker_detector(
            failure_classes=args.classes, conf_threshold=args.conf
        )
    else:
        detector = _build_yolo_detector(
            Path(args.model), failure_classes=args.classes, conf_threshold=args.conf
        )

    report = replay(
        frames,
        detector,
        debounce_window=args.window,
        cooldown_frames=args.cooldown_frames,
        clip_label=str(clip_path),
    )

    if not args.quiet:
        _emit_timeline(report)

    if args.json_out is not None:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(report.to_dict(), indent=2), encoding="utf-8")

    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
